chore(tools): add brew package name to superhtml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -290,6 +290,8 @@ jobs:
         run: ( ( which stylish-haskell ) || ( ( which brew &&  brew install stylish-haskell ) || ( which stack && stack install stylish-haskell ) || ( which cabal && cabal install stylish-haskell ) ) || ( echo "Unable to install tool" ) )
       - name: stylua
         run: ( ( which stylua ) || ( ( which npm && npm i -g @johnnymorganz/stylua-bin ) || ( which cargo && ( cargo binstall stylua || cargo install stylua ) ) || ( which brew &&  brew install stylua ) ) || ( echo "Unable to install tool" ) )
+      - name: superhtml
+        run: ( ( which superhtml ) || ( ( which brew &&  brew install superhtml ) ) || ( echo "Unable to install tool" ) )
       - name: swiftformat
         run: ( ( which swiftformat ) || ( ( which brew &&  brew install swiftformat ) ) || ( echo "Unable to install tool" ) )
       - name: taplo
