feat(tools): add support for pylint

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -204,6 +204,8 @@ jobs:
         run: ( ( which pyflakes ) || ( ( which pipx && pipx install pyflakes ) ) || ( echo "Unable to install tool" ) )
       - name: pyink
         run: ( ( which pyink ) || ( ( which pipx && pipx install pyink ) ) || ( echo "Unable to install tool" ) )
+      - name: pylint
+        run: ( ( which pylint ) || ( ( which pipx && pipx install pylint ) ) || ( echo "Unable to install tool" ) )
       - name: pyupgrade
         run: ( ( which pyupgrade ) || ( ( which pipx && pipx install pyupgrade ) ) || ( echo "Unable to install tool" ) )
       - name: rescript
