feat(tools): add support for jsonpp (#819)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -131,6 +131,8 @@ jobs:
         run: ( ( which jq ) || ( ( which apt-get && sudo apt-get install -y jq ) ) || ( echo "Unable to install tool" ) )
       - name: jqfmt
         run: ( ( which jqfmt ) || ( ( which go && go install github.com/noperator/jqfmt/cmd/jqfmt@latest ) ) || ( echo "Unable to install tool" ) )
+      - name: jsonpp
+        run: ( ( which jsonpp ) || ( ( which brew &&  brew install jsonpp ) ) || ( echo "Unable to install tool" ) )
       - name: julia
         run: ( ( which juliaformatter.jl ) || ( ( which julia && julia  -e 'import Pkg; Pkg.add("JuliaFormatter")' ) ) || ( echo "Unable to install tool" ) )
       - name: just
