test(tools): validate js-beautify

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -138,6 +138,8 @@ jobs:
         run: ( ( which jq ) || ( ( which apt-get && sudo apt-get install -y jq ) ) || ( echo "Unable to install tool" ) )
       - name: jqfmt
         run: ( ( which jqfmt ) || ( ( which go && go install github.com/noperator/jqfmt/cmd/jqfmt@latest ) ) || ( echo "Unable to install tool" ) )
+      - name: js-beautify
+        run: ( ( which js-beautify ) || ( ( which npm && npm i -g js-beautify ) ) || ( echo "Unable to install tool" ) )
       - name: jsonlint
         run: ( ( which jsonlint ) || ( ( which npm && npm i -g jsonlint ) ) || ( echo "Unable to install tool" ) )
       - name: jsonpp
