test: enable previously disabled tool tests (#799)
* test: enable previously disable tool tests

* test(tools): disable fourmolu install again

Installing fourmolu was taking over 3 minutes which is way too long

* test(tools): disable stylish-haskell package install

* test: enable nixpkgs-fmt install

* test(tools): temporarily remove beautysh pip package

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -54,9 +54,6 @@ jobs:
           distribution: temurin
           java-version: "21"
       - uses: haskell-actions/setup@v2
-        with:
-          cabal-version: latest
-          ghc-version: latest
       - uses: julia-actions/cache@v2
       - uses: cargo-bins/cargo-binstall@main
       - name: Install cargo-llvm-cov
@@ -76,6 +73,8 @@ jobs:
         run: ( ( which autoflake ) || ( ( which pipx && pipx install autoflake ) ) || ( echo "Unable to install tool" ) )
       - name: autopep8
         run: ( ( which autopep8 ) || ( ( which pipx && pipx install autopep8 ) ) || ( echo "Unable to install tool" ) )
+      - name: beautysh
+        run: ( ( which beautysh ) || ( ( which brew &&  brew install beautysh ) ) || ( echo "Unable to install tool" ) )
       - name: biome
         run: ( ( which biome ) || ( ( which npm && npm i -g @biomejs/biome ) ) || ( echo "Unable to install tool" ) )
       - name: black
@@ -110,6 +109,8 @@ jobs:
         run: ( ( which goimports ) || ( ( which go && go install golang.org/x/tools/cmd/goimports@latest ) ) || ( echo "Unable to install tool" ) )
       - name: golines
         run: ( ( which golines ) || ( ( which go && go install github.com/segmentio/golines@latest ) ) || ( echo "Unable to install tool" ) )
+      - name: hindent
+        run: ( ( which hindent ) || ( ( which apt-get && sudo apt-get install -y hindent ) || ( which stack && stack install hindent ) ) || ( echo "Unable to install tool" ) )
       - name: html-beautify
         run: ( ( which html-beautify ) || ( ( which npm && npm i -g js-beautify ) ) || ( echo "Unable to install tool" ) )
       - name: htmlbeautifier
@@ -140,6 +141,8 @@ jobs:
         run: ( ( which markdownlint ) || ( ( which npm && npm i -g markdownlint-cli ) ) || ( echo "Unable to install tool" ) )
       - name: markdownlint-cli2
         run: ( ( which markdownlint-cli2 ) || ( ( which npm && npm i -g markdownlint-cli2 ) || ( which brew &&  brew install markdownlint-cli2 ) ) || ( echo "Unable to install tool" ) )
+      - name: nixpkgs-fmt
+        run: ( ( which nixpkgs-fmt ) || ( ( which cargo && ( cargo binstall nixpkgs-fmt || cargo install nixpkgs-fmt ) ) ) || ( echo "Unable to install tool" ) )
       - name: npm-groovy-lint
         run: ( ( which npm-groovy-lint ) || ( ( which npm && npm i -g npm-groovy-lint ) ) || ( echo "Unable to install tool" ) )
       - name: ocamlformat
@@ -216,6 +219,8 @@ jobs:
         run: ( ( which yamlfmt ) || ( ( which go && go install github.com/google/yamlfmt/cmd/yamlfmt@latest ) ) || ( echo "Unable to install tool" ) )
       - name: yapf
         run: ( ( which yapf ) || ( ( which pipx && pipx install yapf ) ) || ( echo "Unable to install tool" ) )
+      - name: yew-fmt
+        run: ( ( which yew-fmt ) || ( ( which cargo && ( cargo binstall yew-fmt || cargo install yew-fmt ) ) ) || ( echo "Unable to install tool" ) )
       - name: Run tests
         run: cargo test
       - name: Generate code coverage
