test(tools): validate reorder-python-imports (#920)
* test(tools): validate reorder-python-imports

* chore: updated generated code

* chore: update test workflow

* test: update expected reorder-python-imports output

---------

Co-authored-by: hougesen <hougesen@users.noreply.github.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -215,6 +215,8 @@ jobs:
         run: ( ( which pylint ) || ( ( which pipx && pipx install pylint ) ) || ( echo "Unable to install tool" ) )
       - name: pyupgrade
         run: ( ( which pyupgrade ) || ( ( which pipx && pipx install pyupgrade ) ) || ( echo "Unable to install tool" ) )
+      - name: reorder-python-imports
+        run: ( ( which reorder-python-imports ) || ( ( which pipx && pipx install reorder-python-imports ) ) || ( echo "Unable to install tool" ) )
       - name: rescript
         run: ( ( which rescript ) || ( ( which npm && npm i -g rescript ) ) || ( echo "Unable to install tool" ) )
       - name: rubocop
