test(tools): add tests for mago:lint and mago:format (#823)
* test(tools): add test for mago:format

* test(tools): add test for mago:lint

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -147,6 +147,8 @@ jobs:
         run: ( ( which lua-format ) || ( ( which luarocks && luarocks install luaformatter ) ) || ( echo "Unable to install tool" ) )
       - name: mado
         run: ( ( which mado ) || ( ( which brew && brew tap akiomik/mado https://github.com/akiomik/mado.git && brew install mado ) ) || ( echo "Unable to install tool" ) )
+      - name: mago
+        run: ( ( which mago ) || ( ( which cargo && ( cargo binstall mago || cargo install mago ) ) || ( which brew &&  brew install mago ) || ( which composer && composer require carthage-software/mago ) ) || ( echo "Unable to install tool" ) )
       - name: markdownfmt
         run: ( ( which markdownfmt ) || ( ( which go && go install github.com/shurcooL/markdownfmt@latest ) ) || ( echo "Unable to install tool" ) )
       - name: markdownlint
