feat(tools): add support for cmake-lint (#768)
Adds support for the cmake linter, cmake-lint, and adds package manager info to a few more plugins

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -73,7 +73,7 @@ jobs:
       - name: fantomas
         run: ( ( which fantomas ) || ( ( which dotnet && dotnet tool install -g fantomas ) ) || ( echo "Unable to install tool" ) )
       - name: ocp-indent
-        run: ( ( which ocp-indent ) || ( ( which apt-get && sudo apt-get install -y ocp-indent ) ) || ( echo "Unable to install tool" ) )
+        run: ( ( which ocp-indent ) || ( ( which apt-get && sudo apt-get install -y ocp-indent ) || ( which opam && eval $(opam env) && opam install ocp-indent ) ) || ( echo "Unable to install tool" ) )
       - name: hurlfmt
         run: ( ( which hurlfmt ) || ( ( which cargo && ( cargo binstall hurlfmt || cargo install hurlfmt ) ) ) || ( echo "Unable to install tool" ) )
       - name: csscomb
@@ -93,11 +93,11 @@ jobs:
       - name: sql-formatter
         run: ( ( which sql-formatter ) || ( ( which npm && npm i -g sql-formatter ) ) || ( echo "Unable to install tool" ) )
       - name: ormolu
-        run: ( ( which ormolu ) || ( ( which apt-get && sudo apt-get install -y ormolu ) ) || ( echo "Unable to install tool" ) )
+        run: ( ( which ormolu ) || ( ( which apt-get && sudo apt-get install -y ormolu ) || ( which stack && stack install ormolu ) || ( which cabal && cabal install ormolu ) ) || ( echo "Unable to install tool" ) )
       - name: prisma
         run: ( ( which prisma ) || ( ( which npm && npm i -g prisma ) ) || ( echo "Unable to install tool" ) )
       - name: markdownlint-cli2
-        run: ( ( which markdownlint-cli2 ) || ( ( which npm && npm i -g markdownlint-cli2 ) ) || ( echo "Unable to install tool" ) )
+        run: ( ( which markdownlint-cli2 ) || ( ( which npm && npm i -g markdownlint-cli2 ) || ( which brew &&  brew install markdownlint-cli2 ) ) || ( echo "Unable to install tool" ) )
       - name: blue
         run: ( ( which blue ) || ( ( which pipx && pipx install blue ) ) || ( echo "Unable to install tool" ) )
       - name: markdownfmt
@@ -139,7 +139,7 @@ jobs:
       - name: terraform
         run: ( ( which terraform ) || ( ( which brew && brew tap hashicorp/tap && brew install hashicorp/tap/terraform ) ) || ( echo "Unable to install tool" ) )
       - name: actionlint
-        run: ( ( which actionlint ) || ( ( which go && go install github.com/rhysd/actionlint/cmd/actionlint@latest ) ) || ( echo "Unable to install tool" ) )
+        run: ( ( which actionlint ) || ( ( which go && go install github.com/rhysd/actionlint/cmd/actionlint@latest ) || ( which brew &&  brew install actionlint ) ) || ( echo "Unable to install tool" ) )
       - name: ocamlformat
         run: ( ( which ocamlformat ) || ( ( which opam && eval $(opam env) && opam install ocamlformat ) ) || ( echo "Unable to install tool" ) )
       - name: clang-format
@@ -147,7 +147,7 @@ jobs:
       - name: julia
         run: ( ( which juliaformatter.jl ) || ( ( which julia && julia  -e 'import Pkg; Pkg.add("JuliaFormatter")' ) ) || ( echo "Unable to install tool" ) )
       - name: ruff
-        run: ( ( which ruff ) || ( ( which pipx && pipx install ruff ) ) || ( echo "Unable to install tool" ) )
+        run: ( ( which ruff ) || ( ( which brew &&  brew install ruff ) || ( which pipx && pipx install ruff ) ) || ( echo "Unable to install tool" ) )
       - name: kcl
         run: ( ( which kcl ) || ( ( which go && go install kcl-lang.io/cli/cmd/kcl@latest ) ) || ( echo "Unable to install tool" ) )
       - name: sqlfluff
@@ -159,7 +159,7 @@ jobs:
       - name: auto-optional
         run: ( ( which auto-optional ) || ( ( which pipx && pipx install auto-optional ) ) || ( echo "Unable to install tool" ) )
       - name: taplo
-        run: ( ( which taplo ) || ( ( which npm && npm i -g @taplo/cli ) ) || ( echo "Unable to install tool" ) )
+        run: ( ( which taplo ) || ( ( which npm && npm i -g @taplo/cli ) || ( which cargo && ( cargo binstall taplo-cli || cargo install taplo-cli ) ) || ( which brew &&  brew install taplo ) ) || ( echo "Unable to install tool" ) )
       - name: isort
         run: ( ( which isort ) || ( ( which pipx && pipx install isort ) ) || ( echo "Unable to install tool" ) )
       - name: rescript
@@ -175,7 +175,7 @@ jobs:
       - name: xmlformat
         run: ( ( which xmlformat ) || ( ( which pipx && pipx install xmlformatter ) ) || ( echo "Unable to install tool" ) )
       - name: buf
-        run: ( ( which buf ) || ( ( which npm && npm i -g @bufbuild/buf ) ) || ( echo "Unable to install tool" ) )
+        run: ( ( which buf ) || ( ( which npm && npm i -g @bufbuild/buf ) || ( which brew &&  brew install bufbuild/buf/buf ) ) || ( echo "Unable to install tool" ) )
       - name: prettier
         run: ( ( which prettier ) || ( ( which npm && npm i -g prettier ) ) || ( echo "Unable to install tool" ) )
       - name: rufo
