test(tools): validate yq

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -241,6 +241,8 @@ jobs:
         run: ( ( which yapf ) || ( ( which brew &&  brew install yapf ) || ( which pipx && pipx install yapf ) ) || ( echo "Unable to install tool" ) )
       - name: yew-fmt
         run: ( ( which yew-fmt ) || ( ( which cargo && ( cargo binstall yew-fmt || cargo install yew-fmt ) ) ) || ( echo "Unable to install tool" ) )
+      - name: yq
+        run: ( ( which yq ) || ( ( which brew &&  brew install yq ) || ( which apt-get && sudo apt-get install -y yq ) || ( which go && go install github.com/mikefarah/yq/v4@latest ) ) || ( echo "Unable to install tool" ) )
       - name: Run tests
         run: cargo test
       - name: Generate code coverage
