feat(tools: add support for pymarkdownlnt

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -255,6 +255,8 @@ jobs:
         run: ( ( which pyink ) || ( ( which pipx && pipx install pyink ) ) || ( echo "Unable to install tool" ) )
       - name: pylint
         run: ( ( which pylint ) || ( ( which pipx && pipx install pylint ) ) || ( echo "Unable to install tool" ) )
+      - name: pymarkdownlnt
+        run: ( ( which pymarkdownlnt ) || ( ( which pipx && pipx install pymarkdownlnt ) ) || ( echo "Unable to install tool" ) )
       - name: pyrefly
         run: ( ( which pyrefly ) || ( ( which pipx && pipx install pyrefly ) ) || ( echo "Unable to install tool" ) )
       - name: pyupgrade
